#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
name: Prashant C Chaturvedi
title: Compass
url: "https://pccofvns.github.io"
baseurl: "" #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
plugins:
  - jekyll-gist
gist:
  noscript: false

cv:
  title: Prashant's CV
# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "assets/images/compass.png"
  # author will appear under the avatar (optional)
  author: "Prashant C Chaturvedi"
  # tagline will appear under the title (optional)
  tagline: "A perpetual wanderer"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "pccofvns"
# Tracker
analytics: UA-11391792-7

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false
